name: stock-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - yfinance
  - plotly
  - dash
  - jupyter-dash
  - notebook>=6.4
  - ipykernel
  - pip
  - pip:
      - dash-bootstrap-components
      - jupyterlab
